### ISSUE TITLE
Can't support the async loading options

### ISSUE THREAD

**Issue by tbjgod** [rahulgaba16/searchable-select-dropdown#2]
My select's options is not static existence, it used ajax async loading and update select's innerHTML.
The 'searchable-select-dropdown' components only replace at ready. can't detection from real select element

**Comment by rgabs** [comment]
@tbjgod Instead of updating innerHTML of select tag, try binding the select dropdown list to a vue js  variable. That variable which in turn will be bound to the searchable-select-dropdown and should update automatically. Let me know if it doesn't work for you.
